name = "prismpack"
author = "Prism Community"
version = "develop-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a660e27dafbb97b2289f8228e18f6284be61acfc3c30d672731e638a6acd8f71"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
