name = "prismpack"
author = "Prism Community"
version = "1.0.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9997f0795fa67b1a712f8b70866c2abc67569cfa3d11b5ee3e4c2a97dd0155da"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
