name = "prismpack"
author = "Prism Community"
version = "1.0.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d7030fdc8a774efacb77afc5466454bb585fd65dd70f57e29f25eb075b9417"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
