name = "prismpack"
author = "Prism Community"
version = "1.0.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "626bcafb709d384f1133b5d2ccaf88344b3f2a3b8254ace59ef7bddc6c2e5e82"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
