name = "prismpack"
author = "Prism Community"
version = "1.0.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b565b52ab10965d21c763fde19347d11c7b7c45610691584bdbbbf73774090"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
