name = "prismpack"
author = "Prism Community"
version = "develop-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fdfecc272a7ce11d2d2ca2a48ed3ac76d4826312403ccf7a3160dfe097c57fd"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
