name = "prismpack"
author = "Prism Community"
version = "develop"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4896fe8912fab82effee021c6cd5dcfaad56fcc3a8863a5ad7145918e5e4ef29"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
