name = "prismpack"
author = "Prism Community"
version = "1.0.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a10aba1de2142a3920e5998d9ed13319765f65fbbcd48a87054764c2f29e956"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
