name = "prismpack"
author = "Prism Community"
version = "testing_16-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c8bf98d45ecafb295bfc13abe28756b47f3b9edc3569d53f7bf8225920adf2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
