name = "prismpack"
author = "Prism Community"
version = "playtest_5-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec3abe2c7b6cc7caf31bfc8c282bc8d813f256a3e3af05458c4e27a1880d1064"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
