name = "prismpack"
author = "Prism Community"
version = "testing_17-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae52091d845f333fff2e2126febd40039b9543529b796f6610da01f995ee385"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
