name = "prismpack"
author = "Prism Community"
version = "playtest_2-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee3cdd3fec45bcb645334f9a3f6044a1f65b0911eba5e4ce53e7853be3ebf5e5"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
