name = "prismpack"
author = "Prism Community"
version = "testing_7-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2778511873b21168ba4aaf3eb675ce9116a68306a5e07c05056105ab0d4e5b6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
