name = "prismpack"
author = "Prism Community"
version = "beta_0-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60b02ede941786870798a5e9e73b9730a3d2286bdb8ae73d772d3624e4479f1e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
