name = "prismpack"
author = "Prism Community"
version = "testing_26-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b342489323bd5f0e9b6064ad6506fca1a7917548f1a6da612e5c2e0fb96f0bc"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
