name = "prismpack"
author = "Prism Community"
version = "playtest_7-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "369d2cc068b3949f894461cf1e4ef0b09188b5940d6b9d12d93d2a12e6c07976"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
